DROP TABLE IF EXISTS blog;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE blog (
  id SERIAL PRIMARY KEY,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE todo (
  id SERIAL PRIMARY KEY,
  create_id INTEGER NOT NULL,
  job VARCHAR(300) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  done BOOLEAN NOT NULL DEFAULT FALSE,
  end_date TIMESTAMP,
  FOREIGN KEY (create_id) REFERENCES users (id)
);